backend:
  name: git-gateway
  branch: master
media_folder: 'content/images'
public_folder: '/images'
collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text', required: false }
      - { label: 'Hero Image', name: 'hero_image', widget: 'image', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', required: false }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'notes'
    label: 'Notes'
    folder: 'content/notes'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}'
    fields:
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
